// Generated by CoffeeScript 1.10.0
(function() {
  var entries, feedparser, feeds, node_promise, promises, request;

  feedparser = require('feedparser');

  request = require('request');

  node_promise = require('node-promise');

  feeds = ['http://phiary.me/rss','http://srad.jp/sradjp.rss'];
  
  entries = [];

  promises = feeds.map(function(url) {
    var deferred;
    console.log(("SSS"))
    deferred = node_promise.defer();
    request(url).pipe(new feedparser([]))
    .on('error', console.log.bind(console))
    .on('data', entries.push.bind(entries))
    .on('end', deferred.resolve.bind(deferred));
    return deferred.promise;
  });

  node_promise.when(node_promise.all(promises), function() {
    console.log("AAA")
    return entries.forEach(function(entry) {});
  });

}).call(this);
